import gov.ca.cwds.cpi.cares.model.Participant;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "participant-first-name-provided"
  @rule_type("VALIDATION")  
  @rule_description("First name must be provided")
  
  dialect "mvel"
  agenda-group "ParticipantBusinessRules-validation-agenda"
  when
    participant: Participant(StringUtils.isEmpty(firstName)) 
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", participant: " + participant.id);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("participant.firstName");
    details.setInvalidValue(participant.firstName);
    validationDetailsList.add(details);
end
