import gov.ca.cwds.cpi.cares.model.Participant;

global java.util.Set validationDetailsList

rule "participant-assign-last-updated-id"
  @rule_type("DATA_PROCESSING")
  @rule_description("Last updated ID is assigned to 00T")
  
  dialect "mvel"
  agenda-group "ParticipantBusinessRules-data-processing-agenda"
  when
    participant: Participant(!lastUpdateId.toUpperCase().equals("00T")) 
  then
    participant.setLastUpdateId("00T");
    update(participant);
end
