import gov.ca.cwds.cpi.cares.model.Participant;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "participant-age-validation"
  @rule_type("VALIDATION")  
  @rule_description("Age must be less than 18 years")

  dialect "mvel"
  agenda-group "ParticipantBusinessRules-validation-agenda"
  when
    participant: Participant(
      birthDate == null ||
      birthDate.isBefore(LocalDate.now().minusYears(18))
    )
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", participant: " + participant.id);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("participant.birthDate");
    details.setInvalidValue(participant.birthDate);
    validationDetailsList.add(details);
end