import gov.ca.cwds.cpi.cares.model.Participant;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;

global java.util.Set validationDetailsList

rule "participant-restricted-last-updated-id"
  @rule_type("VALIDATION")  
  @rule_description("Last updated ID can not be 00T")
  
  dialect "mvel"
  agenda-group "ParticipantBusinessRules-validation-agenda"
  when
    participant: Participant(lastUpdateId.toUpperCase().equals("00T"))    
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", participant: " + participant.id);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("participant.lastUpdateId");
    details.setInvalidValue(participant.lastUpdateId);
    validationDetailsList.add(details);
end