global java.util.Set validationDetailsList

rule "referral-di-cresponse-determination-date)

  @doc_description("Response Determination Date must be a valid date or null")
  
  @doc_drools_file("referral-di-response-determination-date.drl")
  @doc_external_documentation("xTools")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category("DataIntegrity")
  @doc_rule_name("REFERRAL-RI-RESPONSE-DETERMINATION-DATE")
  @doc_rule_type(xTool)

  @doc_di_entity(REFERRAL)
  @doc_di_attribute(RESPONSE_DETERMINATION_DATE)
  @doc_di_length(10)
  @doc_di_type(date)
  @doc_di_nullable(true)
  @doc_di_mandatory(false)
  @doc_di_default(null)
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReferralBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
