import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.AddressData;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "address-R-03233"

  @doc_description("R - 03233 Zip+4 codes are four digits")
  
  @doc_external_documentation("docTool")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_type("DocTool")
  @doc_drools_file("address-R-03233.drl")
  @doc_rule_name("ADDRESS-R-03232")
 @doc_rule_category("DataIntegrity")
  
  @doc_doctool_name("R - 03233 Zip+4 codes are four digits")
  @doc_doctool_description("The Zip+4 field must always be blank or contain 4 digits")
  @doc_doctool_access_logic("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
  
  when
    addressData: AddressData(
      zipSuffix != null && 
      (
        !zipSuffix.equals(new Integer(0)) &&
        String.valueOf(zipSuffix).length() != 4
      )
    )
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + ", address: " + addressData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("addressData.zipSuffix");
    details.setInvalidValue(addressData.zipSuffix);
    validationDetailsList.add(details);

end
