global java.util.Set validationDetailsList

rule "address-ri-client-address"

  @doc_description("Address is associated to one or more Client Address")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DataIntegrity")
  @doc_drools_file("address-ri-client-address.drl")
  @doc_rule_name("ADDRESS-RI-CLIENT-ADDRESS")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("")
  @doc_di_attribute("")
  @doc_di_length("")
  @doc_di_type("")
  @doc_di_nullable("")
  @doc_di_mandatory("")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")
	
  @doc_ri_entity("ADDRESS")
  @doc_ri_attribute("ID")
  @doc_ri_cardinality("one to many")
  @doc_ri_relationship("locates")
  @doc_ri_related_entity("CLIENT_ADDRESS")
  @doc_ri_related_attribute("FKADDRS_T")

  @doc_cpi_name("")
  @doc_cpi_description("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
