global java.util.Set validationDetailsList

rule "address-di-state-code-type"

  @doc_description("State Code Type must be valid in SYSTEM_CODE_TABLE/STATE_C")
  
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_type("xTool")
  @doc_drools_file("address-di-state-code-type.drl")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("ADDRESS-DI-STATE-CODE-TYPE")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("STATE_CODE_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("STATE_C")
  @doc_di_validation_sub_category("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
