global java.util.Set validationDetailsList

rule "address-ri-client-address"

  @doc_description("Address is associated to one or more Client Address")
  
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("xTool")
  @doc_drools_file("address-ri-client-address.drl")
  @doc_rule_name("ADDRESS-RI-CLIENT-ADDRESS")
  @doc_rule_category("ReferentialIntegrity")
  
  @doc_ri_entity("ADDRESS")
  @doc_ri_attribute("ID")
  @doc_ri_cardinality("one to many")
  @doc_ri_relationship("locates")
  @doc_ri_related_entity("CLIENT_ADDRESS")
  @doc_ri_related_attribute("FKADDRS_T")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
