global java.util.Set validationDetailsList

rule "address-di-state-code-type"

  @doc_description("State Code Type must be valid in SYS_CD_C/STATE_C")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DataIntegrity")
  @doc_drools_file("address-di-state-code-type.drl")
  @doc_rule_name("ADDRESS-DI-STATE-CODE-TYPE")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("STATE_CODE_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("SYS_CD_C")
  @doc_di_validation_category("STATE_C")
  @doc_di_validation_sub_category("")
	
  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
