global java.util.Set validationDetailsList

rule "address-di-government-entity-type"

  @doc_description("Government Entity Type (county) must be valid in SYS_CD_C/GVR_ENTC")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DataIntegrity")
  @doc_drools_file("address-di-government-entity-type.drl")
  @doc_rule_name("ADDRESS-DI-GOVERNEMENT-ENTITY-TYPE")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("GOVERNMENT_ENTITY_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")
  @doc_di_validation_values("")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cpi_name("")
  @doc_cpi_description("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
