global java.util.Set validationDetailsList

rule "address-di-street-suffix-type"

  @doc_description("Street Suffix must be valid in SYS_CD_C/ST_SFX_C else 0")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DataIntegrity")
  @doc_drools_file("address-di-street-suffix-type.drl")
  @doc_rule_name("ADDRESS-DI-STREET-SUFFIX-TYPE")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("STREET_SUFFIX_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("SYS_CD_C")
  @doc_di_validation_category("ST_SFX_C")
  @doc_di_validation_sub_category("")
	
  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cpi_name("")
  @doc_cpi_description("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
