global java.util.Set validationDetailsList

rule "address-di-foreign-address-indicator"

  @doc_description("Foreign address indicator must by Y or N")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DataIntegrity")
  @doc_drools_file("address-di-foreign-address-indicator.drl")
  @doc_rule_name("ADDRESS-DI-FOREIGN-ADDRESS-INDICATOR")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("FOREIGN_ADDRESS_IND_VAR")
  @doc_di_length("2")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("N")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")
  @doc_di_validation_values("Y, N")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
