global java.util.Set validationDetailsList

rule "address-di-foreign-address-indicator"

  @doc_description("Foreign address indicator must by Y or N")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("address-di-foreign-address-indicator.drl")
  @doc_rule_name("ADDRESS-DI-FOREIGN-ADDRESS-INDICATOR")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("FOREIGN_ADDRESS_IND_VAR")
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("N")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("Y = Yes, N - No")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
