global java.util.Set validationDetailsList

rule "address-di-unit-designator-type"

  @doc_description("Unit Designator must be valid in SYSTEM_CODE_TABLE/UNT_DSGC else 0")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_drools_file("address-di-unit-designator-type.drl")
  @doc_rule_name("ADDRESS-DI-UNIT-DESIGNATOR-TYPE")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("UNIT_DESIGNATOR_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("0")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("UNT_DSGC")
  @doc_di_validation_sub_category("")
  @doc_di_validation_values()
	
  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
