global java.util.Set validationDetailsList

rule "address-di-pre-direction-code"

  @doc_description("Pre Direction Code must be valid or empty")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_type("xTool")
  @doc_drools_file("address-di-pre-direction-code.drl")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("ADDRESS-DI-PRE-DIRECTION-CODE")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("PRE_DIRECTION_TEXT_CODE")
  @doc_di_length("2")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")
  @doc_di_validation_values(" E = East, N = North, NE = NorthEast, NW = NorthWest, S = South, SE = SouthEast, SW = SouthWest, W = West")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
