import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.AddressData;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "address-di-address-id"

  @doc_description("Address Id must be 10 characters")
  
  @doc_external_documentation("xTool")
  @doc_enforcement_location("BRE, ZOS")
  @doc_drools_file("address-di-address-id.drl")
  @doc_rule_category("DataIntegrity")
  @doc_rule_name("ADDRESS-DI-ADDRESS-ID")
  @doc_rule_type(xTool)

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("ID")
  @doc_di_length("10")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
  
  when
    addressData: AddressData(StringUtils.isEmpty(identifier) || identifier.length() < 10)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + ", address: " + addressData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("addressData.identifier");
    details.setInvalidValue(addressData.identifier);
    validationDetailsList.add(details);
end
