rule "reporter-di-mandated-reporter-ind"

  @doc_description("Mandated Reporter indicator must by Y or N")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-mandated-reporter-ind.drl")
  @doc_rule_name("REPORTER-DI-MANDATED-REPORTER-IND")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("MANDATED_REPORTER_IND")
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("N")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("Y = Yes, N - No")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
