import gov.ca.cwds.cpi.cics.model.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;

global java.util.Set validationDetailsList

rule "client-assign-last-updated-id"
  @rule_type("DATA_PROCESSING")  
  @rule_description("Last updated ID is assigned to 00T")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-data-processing-agenda"
  when
    client: Client(
      !clientData.txnHdrStaffId.toUpperCase().equals("00T")
    )
  then
    client.clientData.setTxnHdrStaffId("00T");
    update(client);
end