server:
  port: ${CARES_REST_API_PORT:8090}
  
spring: 
  datasource:    
    url: ${DB_CMS_JDBC_URL:jdbc:db2://localhost:50000/DB0TDEV}
    username: ${DB_CMS_USER:db2inst1}
    password: ${DB_CMS_PASSWORD:db2inst1}
    driverClassName: com.ibm.db2.jcc.DB2Driver  
    validationQuery: SELECT 1  
  jpa:
    database-platform: DB2Platform    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect  
        default_schema: ${DB_CMS_SCHEMA:CWSINT}
        show_sql: true
        format_sql: true

app:
  cics-service:
    base-url: ${CICS_SERVICE_BASE_URL:https://db-1a.nonprod-gateway.cwds.io:9445}
    username: ${CICS_SERVICE_USERNAME:CWDSAPI}
    password: ${CICS_SERVICE_PASSWORD:Cwspwd18}
  geo-service:
    base-url: ${GEO_SERVICE_BASE_URL:http://api-a.sblegacy.cwds.io:8085}
  bre-service:
    base-url: ${BRE_SERVICE_BASE_URL:https://api-a.sblegacy.cwds.io:3006}

spring.jackson.serialization.INDENT_OUTPUT: true

management:
  security:
    enabled: false 
  endpoints:
    web:
      exposure:
        include: '*'
        