import gov.ca.cwds.cics.model.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "client-di-first-name-provided"

  @doc_description("First name must be provided")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DataIntegrity")
  @doc_drools_file("client-di-first-name-provided.drl")
  @doc_rule_name("CLIENT-DI-FIRST-NAME-PROVIDED")
  @doc_rule_category("DataIntegrity")
  
  @doc_di_entity("CLIENT_T")
  @doc_di_attribute("COMMON_FIRST_NAME")
  @doc_di_length("20")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(StringUtils.isEmpty(clientData.comFstNm))    
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.comFstNm");
    details.setInvalidValue(client.clientData.comFstNm);
    validationDetailsList.add(details);
end
