global java.util.Set validationDetailsList

rule "client-di-gender-code"

  @doc_description("Gender Code must be valid")
  
  @doc_drools_file("client-di-gender-code.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category(dataIntegrity)
  @doc_rule_name("CLIENT-DI-GENDER-CODE")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(GENDER-CODE)
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("U")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("F = female, M = male, I = Intersex, U = unkown")
  

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
