global java.util.Set validationDetailsList

rule "client-di-so-unable-to-determine-code"

  @doc_description("Sexual Orientation Unable to Determine Code must be valid")
  
  @doc_drools_file("client-di-so-unable-to-determine-code.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("CLIENT-DI-SO-UNABLE-TO-DETERMINE-CODE")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(SO_UNABLE_TO_DETERMINE_CODE)
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("D = Did Not Ask, C = Client Does Not Know")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
