global java.util.Set validationDetailsList

rule "client-di-birth-date"

  @doc_description("Client date of birth must be a valid date or empty")
  
  @doc_drools_file("client-di-birth-date.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category(dataIntegrity)
  @doc_rule_name("CLIENT-DI-BIRTH-DATE")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(BIRTH_DATE)
  @doc_di_length("4")
  @doc_di_type(date)
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
