global java.util.Set validationDetailsList

rule "client-di-gender-identity"

  @doc_description("Gender Identity must be valid")
  
  @doc_drools_file("client-di-gender-identity.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category(dataIntegrity)
  @doc_rule_name("CLIENT-DI-GENDER-IDENTITY")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(GENDER_IDENTITY)
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("0")
  @doc_di_validation_table(SYSTEM_CODE_TABLE)
  @doc_di_validation_category(CLNT_GIC)
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
