import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;

rule "reporter-di-middle-initial-name"

  @doc_description("Middle initial cannot be more that one character")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-middle-initial-name.drl")
  @doc_rule_name("REPORTER-DI-MIDDLE-INITIAL-NAME")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("MIDDLE_INITIAL_NAME")
  @doc_di_length("1")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default(" ")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	$reporterData: ReporterData(String.valueOf(middleInitialName).length > 1)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.middleInitialName");
    details.setInvalidValue($reporterData.middleInitialName);
    validationDetailsList.add(details);
end
