import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "reporter-di-mandated-reporter-ind"

  @doc_description("Mandated Reporter indicator must by Y or N")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-mandated-reporter-ind.drl")
  @doc_rule_name("REPORTER-DI-MANDATED-REPORTER-IND")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("MANDATED_REPORTER_IND")
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("N")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("Y = Yes, N - No")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
  	reporterData: ReporterData(
      StringUtils.isEmpty(mandatedReporterIndicator) || 
      !mandatedReporterIndicator.matches("Y|N")) 

  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.mandatedReporterIndicator");
    details.setInvalidValue(reporterData.mandatedReporterIndicator);
    validationDetailsList.add(details);

end
