import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList
rule "reporter-di-fklaw_enft"

  @doc_description("FKLAW_ENFT must be null or 10 characters")
  
  @doc_external_documentation("xTool")
  @doc_enforcement_location("BRE")
  @doc_drools_file("reporter-di-fklaw_enft.drl")
  @doc_rule_category("DataIntegrity")
  @doc_rule_name("REPORTER-DI-FKLAW-ENFT")
  @doc_rule_type(xTool)

  @doc_di_entity("REPORTER")
  @doc_di_attribute("FKLAW_ENFT")
  @doc_di_length("10")
  @doc_di_type("string")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  @doc_di_validation_notes("If not null, then must then must be 10 characters")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
  	reporterData: ReporterData(!StringUtils.isEmpty(fkLawEnforcement)  && String.valueOf(fkLawEnforcement).length != 10)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.fkLawEnforcement");
    details.setInvalidValue(reporterData.fkLawEnforcement);
    validationDetailsList.add(details);

end
