import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "reporter-di-drms-mandated-reporter-feedback"

  @doc_description("Mandated Reporter feedback document key must be null or 10 characters")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-mandated-reporter-feedback.drl")
  @doc_rule_name("REPORTER-DI-MANDATED-REPORTER-FEEDBACK")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("DRMS_MANDATED_RPRTR_FEEDBACK")
  @doc_di_length("10")
  @doc_di_type("string")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default("null")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	reporterData: ReporterData(!StringUtils.isEmpty(feedbackDocument) && String.valueOf(feedbackDocument).length != 10)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.feedbackDocument");
    details.setInvalidValue(reporterData.feedbackDocument);
    validationDetailsList.add(details);

end
