import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;
import org.drools.core.util.StringUtils;

rule "reporter-R-03233"

  @doc_description("The Zip+4 field must always be blank or contains 4 digits")
  
  @doc_external_documentation("DocTool")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("DocTool")
  @doc_drools_file("reporter-R-03233.drl")
  @doc_rule_name("REPORTER-R-03233")

  @doc_doctool_name("R - 03233 Zip+4 is four digits")
  @doc_doctool_description("The Zip+4 field must always be blank or contains 4 digits")
  @doc_doctool_access_logic()

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
  	$reporterData: ReporterData(zipSuffixNumber == null || (zipSuffixNumber != 0 && String.valueOf(zipSuffixNumber).length != 4))
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.zipSuffixNumber");
    details.setInvalidValue($reporterData.zipSuffixNumber);
    validationDetailsList.add(details);

end
