import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;

global java.util.Set validationDetailsList

rule "reporter-di-street-name"

  @doc_description("Street name cannot be more than 40 characters")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-street-name.drl")
  @doc_rule_name("REPORTER-DI-STREET-NAME")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("STREET_NAME")
  @doc_di_length("40")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	reporterData: ReporterData(String.valueOf(streetName).length > 40)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.streetName");
    details.setInvalidValue(reporterData.streetName);
    validationDetailsList.add(details);
end
