rule "reporter-di-employer-name"

  @doc_description("Mandatory if the individual is acting as a mandated REPORTER and the employer address is not already associated with an identified LAW_ENFORCEMENT")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-employer-name.drl")
  @doc_rule_name("REPORTER-DI-EMPLOYER-NAME")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("RPTR-EMPNM")
  @doc_di_length("35")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default(" ")
  @doc_di_validation_table()
  @doc_di_validation_category)
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
