import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;

rule "reporter-di-last-name"

  @doc_description("Last name cannot be more than 25 characters")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-last-name.drl")
  @doc_rule_name("REPORTER-DI-LAST-NAME")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("LAST_NAME")
  @doc_di_length("25")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	reporterData: ReporterData(String.valueOf(lastName).length > 25)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.lastName");
    details.setInvalidValue(reporterData.lastName);
    validationDetailsList.add(details);
end
