import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;
import org.drools.core.util.StringUtils;

rule "reporter-R-00846"
  @doc_description("R - 00846 Badge Number Specification")
  @doc_external_documentation("docTools")
  @doc_enforcement_location("BRE")
  @doc_rule_type("DocTool")
  @doc_drools_file("reporter-R-00846.drl")
  @doc_rule_name("REPORTER-R-00846")
  @doc_rule_category(BusinessPolicy)
  
  @doc_doctool_name("R - 00846 Badge Number Specification")
  @doc_doctool_description("BADGE NUMBER may only be specified if the REPORTER is associated with LAW ENFORCEMENT")
  @doc_doctool_access_logic("If Law Enforcement is entered, then Badge Number is enabled, else disabled")
  
  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  when
  	reporterData: ReporterData(!StringUtils.isEmpty(badgeNumber) && StringUtils.isEmpty(fkLawEnforcement))
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_doctool_description") + " : Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("reporterData.badgeNumber");
    details.setInvalidValue(reporterData.badgeNumber);
    validationDetailsList.add(details);
end