rule "reporter-di-reporter-id"

  @doc_description("Reporter Id must be 10 characters")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-reporter-id.drl")
  @doc_rule_name("REPORTER-DI-REPORTER-ID")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("ID")
  @doc_di_length("10")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
