rule "reporter-di-primary-phone-number"

  @doc_description("Primary phone number must be 0 or 10 digits")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-phone-number.drl")
  @doc_rule_name("REPORTER-DI-PHONE-NUMBER")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("PRIMARY_PHONE_NUMBER")
  @doc_di_length("7")
  @doc_di_type("integer")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("0")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
  	$reporterData: ReporterData(primaryPhoneNumber != 0 && String.valueOf(primaryPhoneNumber).length != 10)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.primaryPhoneNumber");
    details.setInvalidValue($reporterData.primaryPhoneNumber);
    validationDetailsList.add(details);
end
