rule "reporter-ri-person"

  @doc_description("Mandatory foreign key that 'is a' person")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("")
  @doc_rule_category("ReferentialIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-ri-referral.drl")
  @doc_rule_name("REPORTER-RI-PERSON")

  @doc_ri_entity("REPORTER")
  @doc_ri_attribute("ID")
  @doc_ri_cardinality("one to one")
  @doc_ri_relationship("has reported")
  @doc_ri_related_entity("PERSON")
  @doc_ri_related_attribute("CWS_XREF_ID")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
