import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "reporter-R-00725"

  @doc_description("R - 00725 Street Name exigency") 
  @doc_external_documentation("docTool Application")
  @doc_enforcement_location("BRE)
  @doc_rule_type("DocTool")
  @doc_drools_file("reporter-R-00725.drl")
  @doc_rule_name("REPORTER-R-00725")
  @doc_rule_category("BusinessPolicy")
  
  @doc_doctool_name("R - 00725 Street Name exigency")
  @doc_doctool_description("If Street Number is entered, then Street Name is mandatory")
  @doc_doctool_access_logic("If REPORTER.Street Number not = null, then REPORTER.Street Name must not be blank")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
    reporterData: ReporterData(!StringUtils.isEmpty(streetNumber) && StringUtils.isEmpty(streetName))
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_doctool_description") + " : Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("reporterData.streetName");
    details.setInvalidValue(reporterData.streetName);
    validationDetailsList.add(details);
end
