import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.AddressData;
import org.drools.core.util.StringUtils;

rule "reporter-di-reporter-id"

  @doc_description("Reporter ID must be 10 characters")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-reporter-id.drl")
  @doc_rule_name("REPORTER-DI-REPORTER-ID")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("ID")
  @doc_di_length("10")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	reporterData: ReporterData(String.valueOf(identifier).length != 10)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.identifier");
    details.setInvalidValue(reporterData.identifier);
    validationDetailsList.add(details);
end
