rule "reporter-di-communication-method-type"

  @doc_description("Communication Method must be 0 or valid")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-communication-method.drl")
  @doc_rule_name("REPORTER-DI-COMMUNICATION-METHOD")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("COMMUNICATION_METHOD")
  @doc_di_length("4")
  @doc_di_type("integer")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("0")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("CMM_MTHC")
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  @doc_di_validation_notes("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
