import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;

rule "reporter-di-communication-method-type"

  @doc_description("Communication Method must be 0 or valid")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-communication-method.drl")
  @doc_rule_name("REPORTER-DI-COMMUNICATION-METHOD")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("COMMUNICATION_METHOD")
  @doc_di_length("4")
  @doc_di_type("integer")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("0")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("CMM_MTHC")
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  @doc_di_validation_notes("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	reporterData: ReporterData(communicationMethod != 0 && communicationMethod != 408 
		&& communicationMethod != 409 && communicationMethod != 410
		&& communicationMethod != 5375 && communicationMethod != 5378)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.communicationMethod");
    details.setInvalidValue(reporterData.communicationMethod);
    validationDetailsList.add(details);

end
