rule "reporter-ri-referral"

  @doc_description("Optional foreign key that 'has reported' the REFERRAL")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("")
  @doc_rule_category("ReferentialIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-ri-referral.drl")
  @doc_rule_name("REPORTER-RI-REFERRAL")

  @doc_ri_entity("REPORTER")
  @doc_ri_attribute("FKREFERL_T")
  @doc_ri_cardinality("zero to one")
  @doc_ri_relationship("has reported")
  @doc_ri_related_entity("REFERRAL")
  @doc_ri_related_attribute("ID")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
