rule "reporter-di-state-code-typ"

  @doc_description("State Code Type must be a space or valid")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-state-code-type.drl")
  @doc_rule_name("REPORTER-DI-STATE-CODE-TYPE")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("STATE_CODE_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("0")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("STATE_C")
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
