import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;

rule "reporter-di-message-phone-extension-number"

  @doc_description("Message phone extension number must be a 0 or consist of three digits")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-message-phone-extension-number.drl")
  @doc_rule_name("REPORTER-DI-MESSAGE-PHONE-EXTENSION-NUMBER")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("MESSAGE_PHONE_EXTENSION_NUMBER")
  @doc_di_length("7")
  @doc_di_type("integer")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("0")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	$reporterData: ReporterData(messagePhoneExtensionNumber == null || (messagePhoneExtensionNumber != 0 && String.valueOf(messagePhoneExtensionNumber).length != 3))
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.messagePhoneExtensionNumber");
    details.setInvalidValue($reporterData.messagePhoneExtensionNumber);
    validationDetailsList.add(details);
end
