rule "reporter-di-required-fields"

  @doc_description("First name, last name, and phone number are required")
  
  @doc_external_documentation("")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("CARES")
  @doc_drools_file("reporter-di-required-fields.drl")
  @doc_rule_name("REPORTER-DI-REQUIRED-FIELDS")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("FIRST_NAME, LAST_NAME, PHONE_NUMBER")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
  $reporterData: ReporterData(StringUtils.isEmpty(firstName) || StringUtils.isEmpty(lastName) || primaryPhoneNumber == 0 || primaryPhoneNumber == null)

  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.firstName  reporterData.lastName  reporterData.primaryPhoneNumber");
    details.setInvalidValue("First name: " + $reporterData.firstName + " Last name: " + $reporterData.lastName + " Phone number: " + $reporterData.primaryPhoneNumber);
    validationDetailsList.add(details);

end
