rule "reporter-di-county-specific-code"

  @doc_description("County Code must be valid")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-county-specific-code.drl")
  @doc_rule_name("REPORTER-DI-COUNTY-SPECIFIC-CODE")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("COUNTY_SPECIFIC_CODE")
  @doc_di_length("2")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("99")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("GVR_ENTC")
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  @doc_di_validation_notes("Use value in USER_DEFINED_LOGICAL_ID column")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

	$reporterData: ReporterData(countySpecificCode == null)
	
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.countySpecificCode");
    details.setInvalidValue($reporterData.countySpecificCode);
    validationDetailsList.add(details);
  
end
