rule "reporter-di-feedback-required-date"

  @doc_description("Feedback required indicator must be blank, Y, or N")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-feedback-required-date.drl")
  @doc_rule_name("REPORTER-DI-FEEDBACK-REQUIRED-DATE")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("FEEDBACK_REQUIRED_IND")
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default(" ")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("Y = Yes, N - No")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
