rule "reporter-R-00725"

  @doc_description("R - 00725 Street Name exigency") 
  @doc_external_documentation("docTool Application")
  @doc_enforcement_location("FE, BFE, ZOS")
  @doc_rule_type("DocTool")
  @doc_drools_file("reporter-R-00725.drl")
  @doc_rule_name("REPORTER-R-00725")
  @doc_rule_category("BusinessPolicy")
  
  @doc_doctool_name("R - 00725 Street Name exigency")
  @doc_doctool_description("If Street Number is entered, then Street Name is mandatory")
  @doc_doctool_access_logic("If REPORTER.Street Number not = null, then REPORTER.Street Name must not be blank")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
