import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;

rule "reporter-di-titel-description"

  @doc_description("Title description must be less than 50 characters")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-title-description.drl")
  @doc_rule_name("REPORTER-DI-TITLE-DESCRIPTION")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("TITLE_DESCRIPTION")
  @doc_di_length("50")
  @doc_di_type("string")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default(" ")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  @doc_di_validation_notes("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
    $reporterData: ReporterData(String.valueOf(titleDescription).length > 50)
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.titleDescription");
    details.setInvalidValue($reporterData.titleDescription);
    validationDetailsList.add(details);

end
