rule "reporter-di-drms-mandated-reporter-feedback"

  @doc_description("Mandated Reporter feedback document pointer must be null or 10 characters")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-mandated-reporter-feedback.drl")
  @doc_rule_name("REPORTER-DI-MANDATED-REPORTER-FEEDBACK")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("DRMS_MANDATED_RPRTR_FEEDBACK")
  @doc_di_length("10")
  @doc_di_type("char")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default("null")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
