rule "reporter-di-feedback-date"

  @doc_description("Feedback date must be null or a valid date")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-feedback-date.drl")
  @doc_rule_name("REPORTER-DI-FEEDBACK-DATE")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("FEEDBACK_DATE")
  @doc_di_length("10")
  @doc_di_type("date")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default("null")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when

  then

end
