import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "reporter-R-03232"

  @doc_description("Zip code must be 5 digits")
  
  @doc_external_documentation("DocTool")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("DocTool")
  @doc_drools_file("reporter-R-03232.drl")
  @doc_rule_name("REPORTER-R-03232")

  @doc_doctool_name("R-03232 Zip Codes are five digits")
  @doc_doctool_description("All zip codes entered must be 5 digits.")
  @doc_doctool_access_logic()

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
   when
  	$reporterData: ReporterData(zipNumber == null || (zipNumber != 0 && String.valueOf(zipNumber).length != 5))
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.zipNumber");
    details.setInvalidValue($reporterData.zipNumber);
    validationDetailsList.add(details);
end
