import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;

rule "reporter-di-state-code-type"

  @doc_description("State Code Type must be a valid")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-state-code-type.drl")
  @doc_rule_name("REPORTER-DI-STATE-CODE-TYPE")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("STATE_CODE_TYPE")
  @doc_di_length("4")
  @doc_di_type("integer")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("0")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("STATE_C")
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
 
	$reporterData: ReporterData(state == null)
	
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + $reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.state");
    details.setInvalidValue($reporterData.state);
    validationDetailsList.add(details);

end
