import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import gov.ca.cwds.cics.model.ReporterData;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "reporter-di-feedback-required-date"

  @doc_description("Feedback required indicator must be blank, Y, or N")
  
  @doc_external_documentation("xTool Application")
  @doc_enforcement_location("BRE")
  @doc_rule_category("DataIntegrity")
  @doc_rule_type("xTool")
  @doc_drools_file("reporter-di-feedback-required-date.drl")
  @doc_rule_name("REPORTER-DI-FEEDBACK-REQUIRED-DATE")

  @doc_di_entity("REPORTER")
  @doc_di_attribute("FEEDBACK_REQUIRED_IND")
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default(" ")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("Y = Yes, N - No")

  dialect "mvel"
  agenda-group "ReporterBusinessRules-validation-agenda"
  
  when
	reporterData: ReporterData(!StringUtils.isEmpty(feedbackRequiredInd) && String.valueOf(feedbackRequiredInd) != "Y" && String.valueOf(feedbackRequiredInd) != "N")
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + " - Reporter: " + reporterData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.CONSTRAINT_VALIDATION);
    details.setProperty("reporterData.feedbackRequiredInd");
    details.setInvalidValue(reporterData.feedbackRequiredInd);
    validationDetailsList.add(details);

end
