global java.util.Set validationDetailsList

rule "template"

  @doc_description("")
  
  @doc_drools_file()
  @doc_external_documentation()
  @doc_enforcement_location()
  @doc_rule_category()
  @doc_rule_name()
  @doc_rule_type()
  
  @doc_doctool_name()
  @doc_doctool_description()
  @doc_doctool_access_logic()

  @doc_di_entity()
  @doc_di_attribute()
  @doc_di_length()
  @doc_di_type()
  @doc_di_nullable()
  @doc_di_mandatory()
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  @doc_ri_entity()
  @doc_ri_attribute()
  @doc_ri_cardinality()
  @doc_ri_relationship()
  @doc_ri_related_entity()
  @doc_ri_related_attribute()
  
  @doc_cares_name()
  @doc_cares_description()
  
  @doc_hot_name()
  @doc_hot_description()
  
  @doc_cals_name()
  @doc_cals_description()
  
  @doc_case_name()
  @doc_case_description()
  

  dialect "mvel"
  agenda-group "BusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
