global java.util.Set validationDetailsList

rule "referral-di-communicaton-method-type"

  @doc_description("Communication Method Type must be valid in SYSTEM_CODE_TABLE/CMM_MTHC")
  
  @doc_drools_file("referral-di-communication-method-type.drl")
  @doc_external_documentation("xTools")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("REFERRAL-RI-COMMUNICATION-METHOD-TYPE")
  @doc_rule_type(xTool)

  @doc_di_entity(REFERRAL)
  @doc_di_attribute(COMMUNICATION_METHOD_TYPE)
  @doc_di_length(4)
  @doc_di_type(smallint)
  @doc_di_nullable(false)
  @doc_di_mandatory(true)
  @doc_di_default()
  @doc_di_validation_table(SYSTEM_CODE_TABLE)
  @doc_di_validation_category(CMM_MTHC)
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReferralBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
