global java.util.Set validationDetailsList

rule "referral-di-government-entity-type"

  @doc_description("Government Entity Type must be valid in SYSTEM_CODE_TABLE/GVR_ENTC")
  
  @doc_drools_file("referral-di-government-entity-type.drl")
  @doc_external_documentation("xTools")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("REFERRAL-RI-GOVERNMENT-ENTITY-TYPE")
  @doc_rule_type(xTool)

  @doc_di_entity(REFERRAL)
  @doc_di_attribute(APPROVAL_STATUS_TYPE)
  @doc_di_length(4)
  @doc_di_type(smallint)
  @doc_di_nullable(false)
  @doc_di_mandatory(false)
  @doc_di_default(0)
  @doc_di_validation_table(SYSTEM_CODE_TABLE)
  @doc_di_validation_category(GVR_ENTC)
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReferralBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
