global java.util.Set validationDetailsList

rule "referral-di-referral-response-type"

  @doc_description("Referral Response Type must be valid in SYSTEM_CODE_TABLE/RFR_RSPC")
  
  @doc_drools_file("referral-di-referral-response-type.drl")
  @doc_external_documentation("xTools")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("REFERRAL-RI-REFERRAL-RESPONSE-TYPE")
  @doc_rule_type(xTool)

  @doc_di_entity(REFERRAL)
  @doc_di_attribute(REFERRAL-RESPONSE-TYPE)
  @doc_di_length(4)
  @doc_di_type(smallint)
  @doc_di_nullable(false)
  @doc_di_mandatory(false)
  @doc_di_default(0)
  @doc_di_validation_table(SYSTEM_CODE_TABLE)
  @doc_di_validation_category(REFR_RSPC)
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReferralBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
