global java.util.Set validationDetailsList

rule "referral-di-responsible-agency-code"

  @doc_description("Reponsible Agency Code must be valid")
  
  @doc_drools_file("referral-di-responsible-agency-code.drl")
  @doc_external_documentation("xTools")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("REFERRAL-DI-RESPONSIBLE-AGENCY-CODE")
  @doc_rule_type(xTool)

  @doc_di_entity(REFERRAL)
  @doc_di_attribute(RESPONSIBLE_AGENCY_CODE)
  @doc_di_length("1")
  @doc_di_type("string")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("C = County Welfare Department, P = Probation, O = Out of State Agency,  A = Private Adoption Agency,  S = State Adoption District Office, I = Indian Child Welfare, K = Ken-Gap, M = Mental Health")

  dialect "mvel"
  agenda-group "ReferralBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
