global java.util.Set validationDetailsList

rule "referral-di-approval-status-type"

  @doc_description("Approval Status Type must be valid in SYSTEM_CODE_TABLE/APV_STC")
  
  @doc_drools_file("referral-di-approval-status-type.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("REFERRAL-RI-APPROVAL-STATUS-TYPE")
  @doc_rule_type(xTool)

  @doc_di_entity(REFERRAL)
  @doc_di_attribute(APPROVAL_STATUS_TYPE)
  @doc_di_length("4"
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("118")
  @doc_di_validation_table(SYSTEM_CODE_TABLE)
  @doc_di_validation_category(APV_STC)
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReferralBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
