global java.util.Set validationDetailsList

rule "referral-di-response-determination-time)

  @doc_description("Response Determination Time must be a valid time or null")
  
  @doc_drools_file("referral-di-response-determination-time.drl")
  @doc_external_documentation("xTools")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category("DataIntegrity")
  @doc_rule_name("REFERRAL-RI-RESPONSE-DETERMINATION-TIME")
  @doc_rule_type(xTool)

  @doc_di_entity(REFERRAL)
  @doc_di_attribute(RESPONSE_DETERMINATION_TIME)
  @doc_di_length(8)
  @doc_di_type(TIME)
  @doc_di_nullable(true)
  @doc_di_mandatory(false)
  @doc_di_default(null)
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()

  dialect "mvel"
  agenda-group "ReferralBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
