global java.util.Set validationDetailsList

rule "client-ri-email-address"

  @doc_description("Email Address")
  
  @doc_drools_file("client-ri-email-address.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category(dataIntegrity)
  @doc_rule_name("CLIENT-DI-EMAIL-ADDRESS")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(EMAIL_ADDRESS)
  @doc_di_length("50")
  @doc_di_type("char")
  @doc_di_nullable("true")
  @doc_di_mandatory("false")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
