//created on: Jan 3, 2019
import gov.ca.cwds.cics.model.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "client-referential-integrity"

  @doc_description("Client Referential Integrity")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("CMS BRE")
  @doc_rule_type("ReferentialIntegrity")
  @doc_drools_file("client-referential-integrity.drl")
  @doc_rule_name("RI-CLIENT")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("")
  @doc_di_attribute("")
  @doc_di_length("")
  @doc_di_type("")
  @doc_di_nullable("")
  @doc_di_mandatory("")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")

  @doc_ri_entity("CLIENT_T")
  @doc_ri_attribute("ID")
  @doc_ri_cardinality("zero to many")
  @doc_ri_relationship("is identified as")
  @doc_ri_related_entity("CHILD_CLIENT")
  @doc_ri_related_attribute("FKCLIENT_T")

  @doc_cpi_name("")
  @doc_cpi_description("")

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end

