global java.util.Set validationDetailsList

rule "client-di-social-security-number"

  @doc_description("Social Security Number")
  
  @doc_drools_file("client-di-social-security-number.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category(dataIntegrity)
  @doc_rule_name("CLIENT-DI-SOCIAL-SECURITY-NUMBER")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(SOCIAL_SECURITY_NUMBER)
  @doc_di_length(9)
  @doc_di_type(char)
  @doc_di_nullable(false)
  @doc_di_mandatory(false)
  @doc_di_default(0)
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
