import gov.ca.cwds.cics.model.client.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "client-last-name-provided"
  @doc_description("Last name must be provided")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("CARES BRE")
  @doc_rule_type("DataIntegrity")
  @doc_drools_file("client-last-name-provided.drl")
  @doc_rule_name("Client last name provided")
  
  @doc_doctool_name("")
  @doc_doctool_description("")
  
  @doc_di_entity("CLIENT_T")
  @doc_di_attribute("COM_LST_NM")
  @doc_di_length("25")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cpi_name("")
  @doc_cpi_description("")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(StringUtils.isEmpty(clientData.comLstNm))    
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.comLstNm");
    details.setInvalidValue(client.clientData.comLstNm);
    validationDetailsList.add(details);
end
