import gov.ca.cwds.cics.model.client.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "client-last-name-provided"
  @rule_type("xTool")  
  @rule_description("Last name must be provided")
  @rule_name("xTool - Last name must be provided")
  @rule_drools_rule("client-last-name-provided.drl")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("CARES BRE")
  
  @doc_doctool_name("")
  @doc_doctool_description("")
  
  @doc_xtool_entity("CLIENT_T")
  @doc_xtool_attribute("COM_LST_NM")
  @doc_xtool_length("25")
  @doc_xtool_type("char")
  @doc_xtool_nullable("false")
  @doc_xtool_mandatory("true")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cip_name("")
  @doc_cip_description("")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(StringUtils.isEmpty(clientData.comLstNm))    
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.comLstNm");
    details.setInvalidValue(client.clientData.comLstNm);
    validationDetailsList.add(details);
end
