import gov.ca.cwds.cics.model.client.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "client-age-validation"
  @doc_description("Any alleged victim(s) must be known or assumed to be under 19 years of age at the time the referral was received")
  
  @doc_external_documentation("docTools")
  @doc_enforcement_location("CMS BRE")
  @doc_rule_type("DocTool")
  @doc_drools_file("client-age-validation.drl")
  @doc_rule_name("R - 05609 Victim must be <19")
  
  @doc_doctool_name("R - 05609 Victim must be <19")
  @doc_doctool_description("Any alleged victim(s) must be known or assumed to be under 19 years of age at the time the referral was received")

  @doc_di_entity("")
  @doc_di_attribute("")
  @doc_di_length("")
  @doc_di_type("")
  @doc_di_nullable("")
  @doc_di_mandatory("")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")
  @doc_ri_validation_table("")
  @doc_ri_validation_category("")
  @doc_ri_validation_sub_category("")

  @doc_cpi_name("")
  @doc_cpi_description("")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(
      clientData.birthDt == null ||
      clientData.birthDt.isBefore(LocalDate.now().minusYears(18))
    )
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.birthDt");
    details.setInvalidValue(client.clientData.birthDt);
    validationDetailsList.add(details);
end