import gov.ca.cwds.cics.model.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "client-di-primary-language-validation"
  @doc_description("Clients Primary Language must be valid in SYSTEM_CODE_TABLE/LANG_TPC")
  
  @doc_external_documentation("xTools")
  @doc_enforcement_location("CMS")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_drools_file("client-di-primary-language-validation.drl")
  @doc_rule_name("CLIENT-DI-PRIMARY-LANGUAGE-VALIDATION")
  @doc_rule_type(xTool)
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_di_entity("CLIENT")
  @doc_di_attribute("PRIMARY_LANGUAGE_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("no")
  @doc_di_mandatory("no")
  @doc_di_default("0")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("LANG_TPC")
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
  