import gov.ca.cwds.cics.model.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;

global java.util.Set validationDetailsList

rule "client-assign-last-updated-id"
  @doc_description("Last updated ID is assigned to 00T")
  
  @doc_external_documentation("")
  @doc_enforcement_location("BRE")
  @doc_rule_type("CARESPlatformIntegration")
  @doc_drools_file("client-assign-last-updated-id.drl")
  @doc_rule_name("CPI-LastUpdateIDAssigned")
  
  @doc_doctool_name("")
  @doc_doctool_description("")
  @doc_di_entity("")
  
  @doc_di_attribute("")
  @doc_di_length("")
  @doc_di_type("")
  @doc_di_nullable("")
  @doc_di_mandatory("")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cpi_name("CPI-LastUpdateIDAssigned")
  @doc_cpi_description("Last updated ID is assigned to 00T")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-data-processing-agenda"
  when
    client: Client(
      !clientData.txnHdrStaffId.toUpperCase().equals("00T")
    )
  then
    client.clientData.setTxnHdrStaffId("00T");
    update(client);
end