global java.util.Set validationDetailsList

rule "client-di-sexual-orientation-type"

  @doc_description("Sexual Orientation Type must be valid")
  
  @doc_drools_file("client-di-sexual-orientation-type.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("CLIENT-DI-SEXUAL-ORIENTATION-TYPE")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(SEXUAL_ORIENTATION_TYPE)
  @doc_di_length("4")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default()
  @doc_di_validation_table(SYSTEM_CODE_TABLE)
  @doc_di_validation_category(CLNT_SOC)
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
