//created on: Jan 3, 2019
import gov.ca.cwds.cics.model.client.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "client-referential-integrity"

  @rule_type("CMSReferentialIntegrity")  
  @rule_description("")
  @rule_name("")
  @rule_drools_rule("client-referential-integrity.drl")
  
  @doc_external_documentation("docTools")
  @doc_enforcement_location("CARES BRE")
  
  @doc_doctool_name("")
  @doc_doctool_description("")

  @doc_xtool_entity("")
  @doc_xtool_attribute("")
  @doc_xtool_length("")
  @doc_xtool_type("")
  @doc_xtool_nullable("")
  @doc_xtool_mandatory("")

  @doc_ri_entity("CLIENT_T")
  @doc_ri_attribute("ID")
  @doc_ri_cardinality("zero to many")
  @doc_ri_relationship("is identified as")
  @doc_ri_related_entity("CHILD_CLIENT")
  @doc_ri_related_attribute("FKCLIENT_T")

  @doc_cip_name("")
  @doc_cip_description("")

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end

