global java.util.Set validationDetailsList

rule "client-di-child-client-ind-var"

  @doc_description("Child Client Indicator must be valid")
  
  @doc_drools_file("client-di-child-client-ind-var.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category(dataIntegrity)
  @doc_rule_name("CLIENT-DI-CHILD-CLIENT-IND-VAR")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(CHILD_CLIENT_IND_VAR)
  @doc_di_length("1")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default("N")
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values("Y = Yes, N = No")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
