import gov.ca.cwds.cics.model.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import org.drools.core.util.StringUtils;

global java.util.Set validationDetailsList

rule "client-di-last-name-provided"
  @doc_description("Last name must be provided")
  
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("xTool")
  @doc_drools_file("client-di-last-name-provided.drl")
  @doc_rule_name("CLIENT-DI-LAST-NAME-PROVIDED")
  @doc_rule_category("DataIntegrity, BusinessPolicy")
  
  @doc_di_entity("CLIENT")
  @doc_di_attribute("COMMON_LAST_NAME")
  @doc_di_length("25")
  @doc_di_type("char")
  @doc_di_nullable("false")
  @doc_di_mandatory("true")
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(StringUtils.isEmpty(clientData.comLstNm))    
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("doc_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.comLstNm");
    details.setInvalidValue(client.clientData.comLstNm);
    validationDetailsList.add(details);
end
