global java.util.Set validationDetailsList

rule "client-di-identifier"

  @doc_description("Client Identifier must be 10 characters")
  
  @doc_drools_file("client-di-identifier.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category(dataIntegrity)
  @doc_rule_name("CLIENT-DI-IDENTIFIER")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(ID)
  @doc_di_length(10)
  @doc_di_type(char)
  @doc_di_nullable(false)
  @doc_di_mandatory(true)
  @doc_di_default()
  @doc_di_validation_table()
  @doc_di_validation_category()
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
