import gov.ca.cwds.cics.model.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "client-restricted-last-updated-id"
  @doc_description("Last updated ID can not be 00T")
  
  @doc_external_documentation("")
  @doc_enforcement_location("BRE")
  @doc_rule_type("CARESPlatformIntegration")
  @doc_drools_file("client-restricted-last-updated-id.drl")
  @doc_rule_name("CPI-LastUpdateIDRestriction")
  
  @doc_doctool_name("")
  @doc_doctool_description("")
  
  @doc_di_entity("")
  @doc_di_attribute("")
  @doc_di_length("")
  @doc_di_type("")
  @doc_di_nullable("")
  @doc_di_mandatory("")
  @doc_di_default("")
  @doc_di_validation_table("")
  @doc_di_validation_category("")
  @doc_di_validation_sub_category("")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cpi_name("CPI-LastUpdateIDRestricted")
  @doc_cpi_description("Last updated ID can not be 00T")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(
      clientData.txnHdrStaffId.toUpperCase().equals("00T")
    )
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.txnHdrStaffId");
    details.setInvalidValue(client.clientData.txnHdrStaffId);
    validationDetailsList.add(details);
end