import gov.ca.cwds.cics.model.client.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "client-restricted-last-updated-id"
  @rule_type("CARESPlatformIntegration")  
  @rule_description("Last updated ID can not be 00T")
  @rule_name("CPI-LastUpdateIDRestriction")
  @rule_drools_rule("client-restricted-last-updated-id.drl")
  
  @doc_external_documentation("")
  @doc_enforcement_location("CARES BRE")
  
  @doc_doctool_name("")
  @doc_doctool_description("")
  
  @doc_xtool_entity("")
  @doc_xtool_attribute("")
  @doc_xtool_length("")
  @doc_xtool_type("")
  @doc_xtool_nullable("")
  @doc_xtool_mandatory("")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cip_name("CPI-LastUpdateIDRestricted")
  @doc_cip_description("Last updated ID can not be 00T")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(
      clientData.txnHdrStaffId.toUpperCase().equals("00T")
    )
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.txnHdrStaffId");
    details.setInvalidValue(client.clientData.txnHdrStaffId);
    validationDetailsList.add(details);
end