import gov.ca.cwds.cics.model.client.Client;
import gov.ca.cwds.rest.exception.IssueDetails;
import gov.ca.cwds.rest.exception.IssueType;
import java.time.LocalDate;

global java.util.Set validationDetailsList

rule "client-age-validation"
  @rule_type("DocTool")  
  @rule_description("Any alleged victim(s) must be known or assumed to be under 19 years of age at the time the referral was received")
  @rule_name("R - 05609 Victim must be <19")
  @rule_drools_rule("client-age-validation.drl")
  
  @doc_external_documentation("docTools")
  @doc_enforcement_location("CARES BRE")
  
  @doc_doctool_name("R - 05609 Victim must be <19")
  @doc_doctool_description("Any alleged victim(s) must be known or assumed to be under 19 years of age at the time the referral was received")

  @doc_xtool_entity("")
  @doc_xtool_attribute("")
  @doc_xtool_length("")
  @doc_xtool_type("")
  @doc_xtool_nullable("")
  @doc_xtool_mandatory("")

  @doc_ri_entity("")
  @doc_ri_attribute("")
  @doc_ri_cardinality("")
  @doc_ri_relationship("")
  @doc_ri_related_entity("")
  @doc_ri_related_attribute("")

  @doc_cip_name("")
  @doc_cip_description("")
  
  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
  when
    client: Client(
      clientData.birthDt == null ||
      clientData.birthDt.isBefore(LocalDate.now().minusYears(18))
    )
  then
    IssueDetails details = new IssueDetails();
    details.setUserMessage(rule.getMetaData().get("rule_description") + ", client: " + client.clientData.identifier);
    details.setCode(drools.getRule().getName());
    details.setType(IssueType.BUSINESS_VALIDATION);
    details.setProperty("client.clientData.birthDt");
    details.setInvalidValue(client.clientData.birthDt);
    validationDetailsList.add(details);
end