global java.util.Set validationDetailsList

rule "client-di-name-type"

  @doc_description("Name Type must be valid")
  
  @doc_drools_file("client-di-name-type.drl")
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE, ZOS")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_rule_name("CLIENT-DI-NAMETYPE")
  @doc_rule_type(xTool)
  
  @doc_di_entity(CLIENT)
  @doc_di_attribute(NAME_TYPE)
  @doc_di_length(4)
  @doc_di_type(smallint)
  @doc_di_nullable(false)
  @doc_di_mandatory(true)
  @doc_di_default()
  @doc_di_validation_table(SYSTEM_CODE_TABLE)
  @doc_di_validation_category(NAME_TPC)
  @doc_di_validation_sub_category()
  @doc_di_validation_values()
  

  dialect "mvel"
  agenda-group "ClientBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
