global java.util.Set validationDetailsList

rule "address-R-09774"

  @doc_description("R - 09774 Set For_Add_Ind_Var = N")
  
  @doc_external_documentation("docTool")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DataProcessing")
  @doc_drools_file("address-R-09774.drl")
  @doc_rule_name("ADDRESS-R-09774")
  @doc_rule_category("DataProcessing")
  
  @doc_doctool_name("R - 09774 Set For_Add_Ind_Var = N")
  @doc_doctool_description("Set Foreign Address Indicator Variable to 'No' when foreign address information does not exist.")
  @doc_doctool_access_logic("Set associated entity .Foreign_Address_Ind_Var = 'N' when FOREIGN_ADDRESS row does not exist.")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
