global java.util.Set validationDetailsList

rule "address-R-04925"

  @doc_description("R - 04925 City Name Mandatory with Domestic Addres")
  
  @doc_external_documentation("docTool Application")
  @doc_enforcement_location("BRE, ZOS")
  @doc_rule_type("DocTool")
  @doc_drools_file("address-R-04925.drl")
  @doc_rule_name("ADDRESS-R-04925")
  @doc_rule_category("BusinessPolicy")
  
  @doc_doctool_name("R - 04925 City Name Mandatory with Domestic Addres")
  @doc_doctool_description("When entering a domestic address, a City Name is required.")
  @doc_doctool_access_logic("ADDRESS.City_Name <> null.")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
