global java.util.Set validationDetailsList

rule "address-di-street-suffix-type"

  @doc_description("Street Suffix must be valid in SYSTEM_CODE_TABLE/ST_SFX_C else 0")
  
  @doc_external_documentation("xTools Application")
  @doc_enforcement_location("FE, BRE")
  @doc_rule_category("DataIntegrity, Validation")
  @doc_drools_file("address-di-street-suffix-type.drl")
  @doc_rule_name("ADDRESS-DI-STREET-SUFFIX-TYPE")
  @doc_rule_type("xTool")

  @doc_di_entity("ADDRESS")
  @doc_di_attribute("STREET_SUFFIX_TYPE")
  @doc_di_length("4")
  @doc_di_type("smallint")
  @doc_di_nullable("false")
  @doc_di_mandatory("false")
  @doc_di_default("")
  @doc_di_validation_table("SYSTEM_CODE_TABLE")
  @doc_di_validation_category("ST_SFX_C")
  @doc_di_validation_sub_category("")

  dialect "mvel"
  agenda-group "AddressBusinessRules-validation-agenda"
    when
        //conditions
    then
        //actions

end
